name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

   - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SCP files
      run: |
        scp -o StrictHostKeyChecking=no -r ./howto/* root@web.herewallet.app:/var/www/here/www/howto
        scp -o StrictHostKeyChecking=no -r ./stemmy/* root@web.herewallet.app:/var/www/here/www/stemmy
        scp -o StrictHostKeyChecking=no -r ./privacypolicy/* root@web.herewallet.app:/var/www/here/www/privacypolicy
        scp -o StrictHostKeyChecking=no -r ./nft/* root@web.herewallet.app:/var/www/here/www/nft
        scp -o StrictHostKeyChecking=no -r ./dist/* root@web.herewallet.app:/var/www/here/www
        scp -o StrictHostKeyChecking=no -r ./dist/landing/* root@web.herewallet.app:/var/www/here/www/landing
