name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Build articles
        run: node blog-builder.js

      - name: Build
        run: yarn build

      - name: Clean cache
        run: rm -rf .parcel-cache

      - name: Build Pager
        run: yarn build:pager

      - name: Clean cache
        run: rm -rf .parcel-cache

      - name: Build Near Landing
        run: yarn build:near

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SCP files
        run: |
          scp -o StrictHostKeyChecking=no -r ./dist-near/* fedor@5.161.137.59:/var/www/here/www
          scp -o StrictHostKeyChecking=no -r ./dist-pager/* fedor@5.161.137.59:/var/www/here/pager
          scp -o StrictHostKeyChecking=no -r ./howto/* fedor@5.161.137.59:/var/www/here/www/howto
          scp -o StrictHostKeyChecking=no -r ./privacypolicy/* fedor@5.161.137.59:/var/www/here/www/privacypolicy
          scp -o StrictHostKeyChecking=no -r ./nft/* fedor@5.161.137.59:/var/www/here/www/nft
          scp -o StrictHostKeyChecking=no -r ./dist/* fedor@5.161.137.59:/var/www/here/www
          scp -o StrictHostKeyChecking=no -r ./dist/landing/* fedor@5.161.137.59:/var/www/here/near
