name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

     - name: Install SSH client
      run: sudo apt-get install openssh-client -y

    - name: SCP files
      run: |
        scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./howto/* root@web.herewallet.app:/var/www/here/www/howto
        scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./stemmy/* root@web.herewallet.app:/var/www/here/www/stemmy
        scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./privacypolicy/* root@web.herewallet.app:/var/www/here/www/privacypolicy
        scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./nft/* root@web.herewallet.app:/var/www/here/www/nft
        scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./dist/* root@web.herewallet.app:/var/www/here/www
        scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./dist/landing/* root@web.herewallet.app:/var/www/here/www/landing
